env: "local"
database:
  driver: "postgres"
  dsn: "postgres://nikitakazunin:1213@localhost:5432/sso_db?sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 10s
auth:
  secret_key: "shortener"